-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/vtmo_image_optimization (
  io_img_name BLOB NOT NULL,
  io_status BLOB DEFAULT 'pending' NOT NULL,
  io_original_size INTEGER UNSIGNED DEFAULT NULL,
  io_optimized_size INTEGER UNSIGNED DEFAULT NULL,
  io_webp_size INTEGER UNSIGNED DEFAULT NULL,
  io_processed_at BLOB DEFAULT NULL,
  io_backend BLOB DEFAULT NULL,
  io_error BLOB DEFAULT NULL,
  io_png_zopfli_size INTEGER UNSIGNED DEFAULT NULL,
  PRIMARY KEY(io_img_name)
);

CREATE INDEX io_status ON /*_*/vtmo_image_optimization (io_status);

CREATE INDEX io_processed_at ON /*_*/vtmo_image_optimization (io_processed_at);


CREATE TABLE /*_*/vtmo_zopfli_thumb_stats (
  zts_id INTEGER UNSIGNED NOT NULL,
  zts_thumb_count INTEGER UNSIGNED DEFAULT 0 NOT NULL,
  zts_bytes_saved BIGINT UNSIGNED DEFAULT 0 NOT NULL,
  zts_updated_at BLOB DEFAULT NULL,
  PRIMARY KEY(zts_id)
);
