-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/vtmo_image_optimization (
  io_img_name VARBINARY(255) NOT NULL,
  io_status VARBINARY(32) DEFAULT 'pending' NOT NULL,
  io_original_size INT UNSIGNED DEFAULT NULL,
  io_optimized_size INT UNSIGNED DEFAULT NULL,
  io_webp_size INT UNSIGNED DEFAULT NULL,
  io_processed_at BINARY(14) DEFAULT NULL,
  io_backend VARBINARY(16) DEFAULT NULL,
  io_error BLOB DEFAULT NULL,
  io_png_zopfli_size INT UNSIGNED DEFAULT NULL,
  INDEX io_status (io_status),
  INDEX io_processed_at (io_processed_at),
  PRIMARY KEY(io_img_name)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/vtmo_zopfli_thumb_stats (
  zts_id INT UNSIGNED NOT NULL,
  zts_thumb_count INT UNSIGNED DEFAULT 0 NOT NULL,
  zts_bytes_saved BIGINT UNSIGNED DEFAULT 0 NOT NULL,
  zts_updated_at BINARY(14) DEFAULT NULL,
  PRIMARY KEY(zts_id)
) /*$wgDBTableOptions*/;
